apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ms-aggr-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - example.host.com
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms-aggr
spec:
  hosts:
    - example.host.com
  gateways:
    - ms-aggr-gateway
  http:
    - match:
        - uri:
            prefix: /api/frontend
      route:
        - destination:
            host: ms-aggr-frontend
            subset: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ms-aggr-destination-rule
spec:
  host: ms-aggr-frontend
  subsets:
    - name: v1
      labels:
        version: v1
---
