apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms-SERVICE_NAME-frontend
spec:
  hosts:
    - ms-SERVICE_NAME-frontend
  gateways:
    - ms-SERVICE_NAME-gateway
  http:
    - match:
        - uri:
            prefix: /api/frontend
      fault:
        abort:
          percentage:
            value: ABORT_PERCENTAGE
          httpStatus: 500
      route:
        - destination:
            host: ms-SERVICE_NAME-frontend
            port:
              number: 80
            subset: v1
---
