apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms-aggr-frontend
spec:
  hosts:
    - "*"
  gateways:
    - ms-aggr
  http:
    - match:
        - uri:
            prefix: /api/frontend
      fault:
        abort:
          percentage:
            value: ABORT_PERCENTAGE
          httpStatus: 500
      route:
        - destination:
            host: SERVICE_NAME
            subset: v1
---
