# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-aggr
  labels:
    account: ms-aggr
---

apiVersion: v1
kind: Service
metadata:
  name: ms-aggr-a
  labels:
    app: ms-aggr-a
    service: ms-aggr-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-aggr-a
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-aggr-a-v1
  labels:
    app: ms-aggr-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-aggr-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-aggr-a
        version: v1
    spec:
      serviceAccountName: ms-aggr
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-aggr-a"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-aggr/a"
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: ms-aggr-b
  labels:
    app: ms-aggr-b
    service: ms-aggr-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-aggr-b
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-aggr-b-v1
  labels:
    app: ms-aggr-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-aggr-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-aggr-b
        version: v1
    spec:
      serviceAccountName: ms-aggr
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-aggr-b"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-aggr/b"
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: ms-aggr-c
  labels:
    app: ms-aggr-c
    service: ms-aggr-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-aggr-c
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-aggr-c-v1
  labels:
    app: ms-aggr-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-aggr-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-aggr-c
        version: v1
    spec:
      serviceAccountName: ms-aggr
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-aggr-c"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-aggr/c"
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: ms-aggr-frontend
  labels:
    app: ms-aggr-frontend
    service: ms-aggr-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-aggr-frontend
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-aggr-frontend-v1
  labels:
    app: ms-aggr-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-aggr-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-aggr-frontend
        version: v1
    spec:
      serviceAccountName: ms-aggr
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          args: [ "info", "http://ms-aggr-a/api/v1/ms-aggr/a", "http://ms-aggr-b/api/v1/ms-aggr/b", "http://ms-aggr-c/api/v1/ms-aggr/c" ]
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-aggr-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-aggr/frontend"
          ports:
            - containerPort: 80
---
