# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-branch
  labels:
    account: ms-branch
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-d
  labels:
    app: ms-branch-d
    service: ms-branch-d
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-branch-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-d
  labels:
    app: ms-branch-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-d
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug"]
        env:
        - name: SERVICE_NAME
          value: "ms-branch-d"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-c
  labels:
    app: ms-branch-c
    service: ms-branch-c
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-branch-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-c
  labels:
    app: ms-branch-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-c
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_BRANCH_D_SERVICE_HOST}:${MS_BRANCH_D_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-branch-c"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-b
  labels:
    app: ms-branch-b
    service: ms-branch-b
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-branch-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-b
  labels:
    app: ms-branch-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-b
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug"]
        env:
        - name: SERVICE_NAME
          value: "ms-branch-b"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-a
  labels:
    app: ms-branch-a
    service: ms-branch-a
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-branch-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-a
  labels:
    app: ms-branch-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-a
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_BRANCH_B_SERVICE_HOST}:${MS_BRANCH_B_SERVICE_PORT}/api/do", "http://${MS_BRANCH_C_SERVICE_HOST}:${MS_BRANCH_C_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-branch-a"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-frontend
  labels:
    app: ms-branch-frontend
    service: ms-branch-frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-branch-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-frontend
  labels:
    app: ms-branch-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-frontend
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_BRANCH_A_SERVICE_HOST}:${MS_BRANCH_A_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-branch-frontend"
        - name: HTTP_ROUTE
          value: "/api/frontend"
        ports:
        - containerPort: 80
---
