# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-book-info
  labels:
    account: ms-book-info
---

# service Book Info Ratings
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-ratings
  labels:
    app: ms-book-info-ratings
    service: ms-book-info-ratings
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-ratings-v1
  labels:
    app: ms-book-info-ratings
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-ratings
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-ratings
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-ratings"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/ratings"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---

# service Book Info Reviews
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-reviews
  labels:
    app: ms-book-info-reviews
    service: ms-book-info-reviews
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v1
  labels:
    app: ms-book-info-reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v1
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/reviews"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
            - name: CALLING_URLS
              value: "http://ms-book-info-ratings/api/v1/book-info/ratings"
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v2
  labels:
    app: ms-book-info-reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v2
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v2
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/reviews"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
            - name: CALLING_URLS
              value: "http://ms-book-info-ratings/api/v1/book-info/ratings"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v3
  labels:
    app: ms-book-info-reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v3
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v3
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/reviews"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
            - name: CALLING_URLS
              value: "http://ms-book-info-ratings/api/v1/book-info/ratings"
          ports:
            - containerPort: 80
---

# service Details
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-details
  labels:
    app: ms-book-info-details
    service: ms-book-info-details
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-details-v1
  labels:
    app: ms-book-info-details
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-details
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-details
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-details"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/details"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---

# service Front-end
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-frontend
  labels:
    app: ms-book-info-frontend
    service: ms-book-info-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-frontend-v1
  labels:
    app: ms-book-info-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-frontend
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-book-info/frontend"
            - name: CALLING_URLS
              value: "http://ms-book-info-reviews/api/v1/ms-book-info/reviews,http://ms-book-info-details/api/v1/ms-book-info/details"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---
