# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-branch
  labels:
    account: ms-branch
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-d
  labels:
    app: ms-branch-d
    service: ms-branch-d
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-branch-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-d-v1
  labels:
    app: ms-branch-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-d
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-branch-d"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-branch/d"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-c
  labels:
    app: ms-branch-c
    service: ms-branch-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-branch-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-c-v1
  labels:
    app: ms-branch-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-c
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-branch-c"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-branch/c"
            - name: LOG_LEVEL
              value: "log_level"
            - name: CALLING_URLS
              value: "http://ms-branch-d/api/v1/ms-branch/d"
          ports:
            - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-b
  labels:
    app: ms-branch-b
    service: ms-branch-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-branch-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-b-v1
  labels:
    app: ms-branch-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-b
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-branch-b"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-branch/b"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-a
  labels:
    app: ms-branch-a
    service: ms-branch-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-branch-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-a-v1
  labels:
    app: ms-branch-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-a
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-branch-a"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-branch/a"
            - name: LOG_LEVEL
              value: "log_level"
            - name: CALLING_URLS
              value: "http://ms-branch-b/api/v1/ms-branch/b,http://ms-branch-c/api/v1/ms-branch/c"
          ports:
            - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-branch-frontend
  labels:
    app: ms-branch-frontend
    service: ms-branch-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-branch-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-branch-frontend-v1
  labels:
    app: ms-branch-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-branch-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-branch-frontend
        version: v1
    spec:
      serviceAccountName: ms-branch
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-branch-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/branch/frontend"
            - name: CALLING_URLS
              value: "http://ms-branch-a/api/v1/ms-branch/a"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---
