# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-book-info
  labels:
    account: ms-book-info
---

# service Book Info Ratings
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-ratings
  labels:
    app: ms-book-info-ratings
    service: ms-book-info-ratings
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-ratings-v1
  labels:
    app: ms-book-info-ratings
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-ratings
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-ratings
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-ratings"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service Book Info Reviews
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-reviews
  labels:
    app: ms-book-info-reviews
    service: ms-book-info-reviews
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v1
  labels:
    app: ms-book-info-reviews
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v1
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://${MS_BOOK_INFO_RATINGS_SERVICE_HOST}:${MS_BOOK_INFO_RATINGS_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v2
  labels:
    app: ms-book-info-reviews
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v2
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v2
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://${MS_BOOK_INFO_RATINGS_SERVICE_HOST}:${MS_BOOK_INFO_RATINGS_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-reviews-v3
  labels:
    app: ms-book-info-reviews
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-book-info-reviews
      version: v3
  template:
    metadata:
      labels:
        app: ms-book-info-reviews
        version: v3
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://${MS_BOOK_INFO_RATINGS_SERVICE_HOST}:${MS_BOOK_INFO_RATINGS_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-reviews"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service Details
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-details
  labels:
    app: ms-book-info-details
    service: ms-book-info-details
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-details-v1
  labels:
    app: ms-book-info-details
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-details
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-details
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-details"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service Product Page
apiVersion: v1
kind: Service
metadata:
  name: ms-book-info-product-page
  labels:
    app: ms-book-info-product-page
    service: ms-book-info-product-page
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-book-info-product-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-book-info-product-page-v1
  labels:
    app: ms-book-info-product-page
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-book-info-product-page
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-book-info-product-page
        version: v1
    spec:
      serviceAccountName: ms-book-info
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://${MS_BOOK_INFO_REVIEWS_SERVICE_HOST}:${MS_BOOK_INFO_REVIEWS_SERVICE_PORT}/api/do", "http://${MS_BOOK_INFO_DETAILS_SERVICE_HOST}:${MS_BOOK_INFO_DETAILS_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-book-info-product-page
            - name: HTTP_ROUTE
              value: "/api/frontend"
          ports:
            - containerPort: 80
---