# cdb = Cache + DataBase
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-cdb
  labels:
    account: ms-cdb
---

# service DB
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-db
  labels:
    app: ms-cdb-db
    service: ms-cdb-db
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-db
  labels:
    app: ms-cdb-db
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-db
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-db
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "debug" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-db"
            - name: HTTP_ROUTE
              value: "/api/database"
          ports:
            - containerPort: 80
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-d
  labels:
    app: ms-cdb-d
    service: ms-cdb-d
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-d
  labels:
    app: ms-cdb-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-d
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "debug", "http://${MS_CDB_DB_SERVICE_HOST}:${MS_CDB_DB_SERVICE_PORT}/api/database" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-d"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-c
  labels:
    app: ms-cdb-c
    service: ms-cdb-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-c
  labels:
    app: ms-cdb-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-c
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "debug", "http://${MS_CDB_DB_SERVICE_HOST}:${MS_CDB_DB_SERVICE_PORT}/api/database" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-c"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-b
  labels:
    app: ms-cdb-b
    service: ms-cdb-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-b
  labels:
    app: ms-cdb-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-b
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-b"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-a
  labels:
    app: ms-cdb-a
    service: ms-cdb-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-a
  labels:
    app: ms-cdb-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-a
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://${MS_CDB_C_SERVICE_HOST}:${MS_CDB_C_SERVICE_PORT}/api/do", "http://${MS_CDB_D_SERVICE_HOST}:${MS_CDB_D_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-a"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-cdb-frontend
  labels:
    app: ms-cdb-frontend
    service: ms-cdb-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-cdb-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cdb-frontend
  labels:
    app: ms-cdb-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-cdb-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-cdb-frontend
        version: v1
    spec:
      serviceAccountName: ms-cdb
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "debug", "http://${MS_CDB_A_SERVICE_HOST}:${MS_CDB_A_SERVICE_PORT}/api/do", "http://${MS_CDB_B_SERVICE_HOST}:${MS_CDB_B_SERVICE_PORT}/api/do" ]
          env:
            - name: SERVICE_NAME
              value: "ms-cdb-frontend"
            - name: HTTP_ROUTE
              value: "/api/frontend"
          ports:
            - containerPort: 80
---
