apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-proxy
  labels:
    account: ms-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-a
  labels:
    app: ms-proxy-a
    service: ms-proxy-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-proxy-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-a-v1
  labels:
    app: ms-proxy-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-a
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22590
            - containerPort: 14680
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-a"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-proxy/a"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-b
  labels:
    app: ms-proxy-b
    service: ms-proxy-b
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ms-proxy-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-b-v1
  labels:
    app: ms-proxy-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-b
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22590
            - containerPort: 14680
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-b"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-proxy/b"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-c
  labels:
    app: ms-proxy-c
    service: ms-proxy-c
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ms-proxy-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-c-v1
  labels:
    app: ms-proxy-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-c
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22590
            - containerPort: 14680
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-c"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-proxy/c"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-frontend
  labels:
    app: ms-proxy-frontend
    service: ms-proxy-frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ms-proxy-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-frontend-v1
  labels:
    app: ms-proxy-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-frontend
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22590
            - containerPort: 14680
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-proxy/frontend"
            - name: CALLING_URLS
              value: "http://ms-proxy-a/api/v1/ms-proxy/a,http://ms-proxy-b/api/v1/ms-proxy/b,http://ms-proxy-c/api/v1/ms-proxy/c"
            - name: LOG_LEVEL
              value: "log_level"
          ports:
            - containerPort: 80
---
