apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-proxy
  labels:
    account: ms-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-a
  labels:
    app: ms-proxy-a
    service: ms-proxy-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-proxy-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-a
  labels:
    app: ms-proxy-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-a
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-a"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-b
  labels:
    app: ms-proxy-b
    service: ms-proxy-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-proxy-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-b
  labels:
    app: ms-proxy-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-b
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-b"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-c
  labels:
    app: ms-proxy-c
    service: ms-proxy-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-proxy-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-c
  labels:
    app: ms-proxy-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-c
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-c"
            - name: HTTP_ROUTE
              value: "/api/do"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-proxy-frontend
  labels:
    app: ms-proxy-frontend
    service: ms-proxy-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-proxy-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-proxy-frontend
  labels:
    app: ms-proxy-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-proxy-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-proxy-frontend
        version: v1
    spec:
      serviceAccountName: ms-proxy
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          args: [ "info", "http://${MS_PROXY_A_SERVICE_HOST}:${MS_PROXY_A_SERVICE_PORT}/api/do", "http://${MS_PROXY_B_SERVICE_HOST}:${MS_PROXY_B_SERVICE_PORT}/api/do", "http://${MS_PROXY_C_SERVICE_HOST}:${MS_PROXY_C_SERVICE_PORT}/api/do" ]
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-proxy-frontend"
            - name: HTTP_ROUTE
              value: "/api/frontend"
          ports:
            - containerPort: 80
---
