# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-share
  labels:
    account: ms-share
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-share-d
  labels:
    app: ms-share-d
    service: ms-share-d
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-share-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-d
  labels:
    app: ms-share-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-d
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug"]
        env:
        - name: SERVICE_NAME
          value: "ms-share-d"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-share-c
  labels:
    app: ms-share-c
    service: ms-share-c
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-share-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-c
  labels:
    app: ms-share-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-c
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_SHARE_D_SERVICE_HOST}:${MS_SHARE_D_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-share-c"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-share-b
  labels:
    app: ms-share-b
    service: ms-share-b
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-share-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-b
  labels:
    app: ms-share-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-b
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug"]
        env:
        - name: SERVICE_NAME
          value: "ms-share-b"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-share-a
  labels:
    app: ms-share-a
    service: ms-share-a
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-share-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-a
  labels:
    app: ms-share-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-a
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_SHARE_B_SERVICE_HOST}:${MS_SHARE_B_SERVICE_PORT}/api/do", "http://${MS_SHARE_C_SERVICE_HOST}:${MS_SHARE_C_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-share-a"
        - name: HTTP_ROUTE
          value: "/api/do"
        ports:
        - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-share-frontend
  labels:
    app: ms-share-frontend
    service: ms-share-frontend
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ms-share-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-frontend
  labels:
    app: ms-share-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-frontend
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
      - name: houyi-agent
        image: houyitracing/houyi-agent
        imagePullPolicy: Always
        ports:
        - containerPort: 5775
        - containerPort: 5778
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 14271
      - name: ms-http
        image: houyitracing/ms-http
        imagePullPolicy: Always
        args: ["debug", "http://${MS_SHARE_A_SERVICE_HOST}:${MS_SHARE_A_SERVICE_PORT}/api/do", "http://${MS_SHARE_C_SERVICE_HOST}:${MS_SHARE_C_SERVICE_PORT}/api/do"]
        env:
        - name: SERVICE_NAME
          value: "ms-share-frontend"
        - name: HTTP_ROUTE
          value: "/api/frontend"
        ports:
        - containerPort: 80
---
