# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-share
  labels:
    account: ms-share
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-share-d
  labels:
    app: ms-share-d
    service: ms-share-d
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-share-d
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-d-v1
  labels:
    app: ms-share-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-d
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-share-d"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-share/d"
          ports:
            - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-share-c
  labels:
    app: ms-share-c
    service: ms-share-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-share-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-c-v1
  labels:
    app: ms-share-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-c
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://ms-share-d/api/v1/ms-share/d" ]
          env:
            - name: SERVICE_NAME
              value: "ms-share-c"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-share/c"
          ports:
            - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-share-b
  labels:
    app: ms-share-b
    service: ms-share-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-share-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-b-v1
  labels:
    app: ms-share-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-b
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info" ]
          env:
            - name: SERVICE_NAME
              value: "ms-share-b"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-share/b"
          ports:
            - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-share-a
  labels:
    app: ms-share-a
    service: ms-share-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-share-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-a-v1
  labels:
    app: ms-share-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-a
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://ms-share-b/api/v1/ms-share/b", "http://ms-share-c/api/v1/ms-share/c" ]
          env:
            - name: SERVICE_NAME
              value: "ms-share-a"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-share/a"
          ports:
            - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-share-frontend
  labels:
    app: ms-share-frontend
    service: ms-share-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-share-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-share-frontend-v1
  labels:
    app: ms-share-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-share-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-share-frontend
        version: v1
    spec:
      serviceAccountName: ms-share
      containers:
        - name: houyi-agent
          image: houyitracing/houyi-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          args: [ "info", "http://ms-share-a", "http://ms-share-c/api/v1/ms-share/c" ]
          env:
            - name: SERVICE_NAME
              value: "ms-share-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/share/frontend"
          ports:
            - containerPort: 80
---
