# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-tree
  labels:
    account: ms-tree
---

# service E
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-e
  labels:
    app: ms-tree-e
    service: ms-tree-e
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-e-v1
  labels:
    app: ms-tree-e
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-e
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-e
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-e"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-tree/e"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---

# service D
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-d
  labels:
    app: ms-tree-d
    service: ms-tree-d
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-d-v1
  labels:
    app: ms-tree-d
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-d
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-d
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-d"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-tree/d"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---

# service C
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-c
  labels:
    app: ms-tree-c
    service: ms-tree-c
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-c-v1
  labels:
    app: ms-tree-c
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-c
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-c
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-c"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-tree/c"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---

# service B
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-b
  labels:
    app: ms-tree-b
    service: ms-tree-b
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-b-v1
  labels:
    app: ms-tree-b
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-b
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-b
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-b"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-tree/b"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
            - name: CALLING_URLS
              value: "http://ms-tree-c/api/v1/ms-tree/c,http://ms-tree-d/api/v1/ms-tree/d"
          ports:
            - containerPort: 80
---

# service A
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-a
  labels:
    app: ms-tree-a-v1
    service: ms-tree-a
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-a
  labels:
    app: ms-tree-a
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-a
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-a"
            - name: HTTP_ROUTE
              value: "/api/v1/ms-tree/a"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
            - name: CALLING_URLS
              value: "http://ms-tree-b/api/v1/ms-tree/b,http://ms-tree-e/api/v1/ms-tree/e"
          ports:
            - containerPort: 80
---

# frontend
apiVersion: v1
kind: Service
metadata:
  name: ms-tree-frontend
  labels:
    app: ms-tree-frontend
    service: ms-tree-frontend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: ms-tree-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tree-frontend-v1
  labels:
    app: ms-tree-frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: ms-tree-frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tree-frontend
        version: v1
    spec:
      serviceAccountName: ms-tree
      containers:
        - name: houyi-agent
          image: houyitracing/agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
            - containerPort: 5778
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14271
        - name: ms-http
          image: houyitracing/ms-http
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "ms-tree-frontend"
            - name: HTTP_ROUTE
              value: "/api/v1/tree/frontend"
            - name: CALLING_URLS
              value: "http://ms-tree-a/api/v1/ms-tree/a"
            - name: SAMPLER_TYPE
              value: "sampler_type"
            - name: LOG_LEVEL
              value: "log_level"
            - name: MAX_TRACES_PER_SECOND
              value: "max_traces_per_second"
            - name: ALWAYS_SAMPLE
              value: "always_sample"
            - name: SAMPLING_RATE
              value: "sampling_rate"
          ports:
            - containerPort: 80
---
